"""Rebuild snippets/swe-patches-data.jsx from the SWE-agent example's cached answers.

    uv run --extra sql python docs-site/make_swe_patches_data.py     # from the repo root; asks nothing (HUNCH_MAX_COST=0)

PATCH_PUZZLES: five real runs, each with the issue's title, the agent's words where it says it is done, the
start of its patch (trimmed, and marked so), whether the tests passed (the dataset's `target`) and the question's
p(passes).

PASS_BY_P: every run grouped by that p, with the share that passed weighted to the real pass rate (the spec's
`weights`, as `hunch test` does) and the question's average p, for the picture.
"""
import json
import os
import re
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
from hunch import core  # noqa: E402

PUZZLES = {  # run id: (which of the last three messages holds the claim, why it is here)
    "nficano__humps-194#78": (-2, "The agent's own check printed `size`, where the issue asks for `size_x`, "
                                  "and it called that fixed."),
    "konradhalas__dacite-216#148": (-2, "One deleted line, and the tests passed."),
    "pior__pyramid_useragent-3#26": (-2, "The patch guards `self.string`, but the next line still hands the "
                                         "original `string`, which can be `None`, to `re.findall`. hunch leaned yes."),
    "iterative__dvc-8425#34": (-1, "The patch adds a new script that imitates the bug. The project's own code is "
                                   "untouched."),
    "serge-sans-paille__gast-59#160": (-2, "The patch adds one import line, and the tests passed. hunch doubted "
                                           "it, rightly unsure."),
}
MAX_PATCH_LINES = 12

project = core.load_project(Path("prototype/examples/swe_agent/patch_eval.yml"))
res = core.execute(project)["patch_eval"]
runs = {}
for it in res["items"]:
    runs.setdefault(it["id"], {"row": it["row"]})[it["qid"]] = res["answers"][it["key"]]["noul"]


def prose(text: str) -> str:
    """A message without its code blocks (the agent's commands), on one line."""
    return " ".join(re.sub(r"```.*?```", " ", text, flags=re.S).split())


def patch_lines(patch: str) -> tuple[list[str], int]:
    lines = [ln for ln in patch.strip("\n").split("\n")
             if not ln.startswith(("diff --git", "index ", "--- ", "new file mode"))]
    lines = [ln.replace("+++ b/", "file: ", 1) if ln.startswith("+++ ") else ln for ln in lines]
    while lines and not lines[-1].strip():
        lines.pop()
    return lines[:MAX_PATCH_LINES], max(0, len(lines) - MAX_PATCH_LINES)


out = []
for rid, (msg, why) in PUZZLES.items():
    r = runs[rid]
    lines, cut = patch_lines(r["row"]["patch"])
    out.append({"issue": r["row"]["issue"].split("\n", 1)[0].strip(), "says": prose(r["row"]["final_messages"].split("\n---\n")[msg]),
                "patch": lines, "cut": cut, "passed": int(r["row"]["resolved"] == "yes"),
                "p": round(r["passes_tests"], 2), "claims": round(r["claims_fixed"], 2), "why": why})
    print(f"{rid:34s} passed={out[-1]['passed']} p={out[-1]['p']} claims={out[-1]['claims']} cut={cut}")
    print("   says:", out[-1]["says"][:150])

BUCKETS = [(0, 0.2), (0.2, 0.4), (0.4, 0.6), (0.6, 1.01)]
bars = []
for lo, hi in BUCKETS:
    rs = [r for r in runs.values() if lo <= r["passes_tests"] < hi]
    w = [float(r["row"]["_w"]) for r in rs]
    passed = sum(wi for wi, r in zip(w, rs) if r["row"]["resolved"] == "yes") / sum(w)
    mean_p = sum(wi * r["passes_tests"] for wi, r in zip(w, rs)) / sum(w)
    label = f"{lo:.1f}–{hi:.1f}" if hi <= 1 else f"{lo:.1f} and up"
    bars.append([label, len(rs), round(passed, 3), round(mean_p, 3)])
    print(f"p {label:12s} n={len(rs):3d}  passed (real mix) {passed:.1%}  hunch's average p {mean_p:.2f}")

dest = Path(__file__).parent / "snippets" / "swe-patches-data.jsx"
dest.write_text("// Generated by docs-site/make_swe_patches_data.py from prototype/examples/swe_agent (SWE-agent "
                "trajectories, Nebius, CC BY 4.0). Do not edit.\n"
                f"export const PATCH_PUZZLES = {json.dumps(out, ensure_ascii=False, separators=(',', ':'))};\n"
                f"export const PASS_BY_P = {json.dumps(bars, separators=(',', ':'))};\n")
print(f"{len(out)} puzzles, {len(bars)} bars -> {dest} ({dest.stat().st_size // 1024} KB)")
