"""Rebuild snippets/discovery-data.jsx from the discovery example's cached answers.

    uv run --extra sql python docs-site/make_discovery_data.py     # from the repo root, after fetch.py; asks nothing

Every number is weighted to the 455,449-message collection, as in measure.py (whose readers it reuses). It writes:
- DISCOVERY_FOUND: for drilling, the share of relevant messages each wording finds when it says yes at p >= 0.5;
- DISCOVERY_READ: per topic, how much of what the lawyers wanted a reviewer has found after reading the top X% of
  the collection by p(yes), for both wordings, every half percent, and where measure.py's broad keyword query lands.
"""
import csv
import json
import re
import sys
from pathlib import Path

import numpy as np

EXAMPLE = Path("prototype/examples/discovery")
sys.path.insert(0, str(EXAMPLE))
import measure  # noqa: E402  (sets HUNCH_MAX_COST=0 before importing hunch)

csv.field_size_limit(10**8)
TOPICS = {"drilling": "Oil and gas drilling", "privileged": "Privileged", "lobbying": "Lobbying"}  # spills: too few


def found(y, w, s, read):
    """Recall after reading the top `read` share of the collection (by weight), highest score first."""
    o = np.argsort(-s, kind="stable")
    cw, cy = np.cumsum(w[o]) / w.sum(), np.cumsum((w * y)[o]) / (w * y).sum()
    return [round(float(cy[min(np.searchsorted(cw, r), len(cy) - 1)]) * 100, 1) if r > 0 else 0.0 for r in read]


def rec(y, w, pick):
    """% of the relevant messages among those picked."""
    return round(float((w * y * pick).sum() / (w * y).sum()) * 100, 1)


grid = [i / 200 for i in range(201)]  # 0%, 0.5%, ... 100%
read_data, found_data = {}, None
for name, title in TOPICS.items():
    rows = list(csv.DictReader(open(EXAMPLE / f".cache/{name}.csv")))
    y = np.array([r["gold"] == "yes" for r in rows], float)
    w = 1 / np.array([float(r["stratum"]) for r in rows])
    s = {k: np.array([d[r["id"]] for r in rows]) for k, d in
         (("request", measure.p_yes(EXAMPLE / f"request_only/{name}.yml")), ("protocol", measure.p_yes(EXAMPLE / f"{name}.yml")))}
    kw = np.array([bool(re.search(measure.KEYWORDS[name], (r["email"] + r["attachments"]).lower())) for r in rows], float)
    read_data[name] = {"title": title, "total": round(float(w.sum())), "relevant": round(float((w * y).sum())),
                       "protocol": found(y, w, s["protocol"], grid), "request": found(y, w, s["request"], grid),
                       "keywords": [round(float((w * kw).sum() / w.sum()) * 100, 1), rec(y, w, kw)]}
    if name == "drilling":
        found_data = [["The request's words", rec(y, w, (s["request"] >= 0.5).astype(float))],
                      ["The lawyer's reading", rec(y, w, (s["protocol"] >= 0.5).astype(float))]]
    print(name, "keywords", read_data[name]["keywords"], "80% at",
          next(g for g, v in zip(grid, read_data[name]["protocol"]) if v >= 80))

dest = Path(__file__).parent / "snippets" / "discovery-data.jsx"
dest.write_text("// Generated by docs-site/make_discovery_data.py from prototype/examples/discovery (TREC 2010 Legal Track; "
                "EDRM Enron Email Data Set v2, ZL Technologies, CC BY 3.0 US). Do not edit.\n"
                f"export const DISCOVERY_FOUND = {json.dumps(found_data)};\n"
                f"export const DISCOVERY_READ = {json.dumps(read_data, separators=(',', ':'))};\n")
print(found_data, "->", dest)
