"""Rebuild snippets/command-guard-data.jsx from the command guard example's cached answers.

    uv run --extra sql python docs-site/make_command_guard_data.py    # from the repo root; asks nothing (HUNCH_MAX_COST=0)

Needs the Trace Commons sessions (see prototype/examples/claude_code/NOTICE.md) and the answers already in the store
(`hunch run prototype/examples/claude_code/command_guard.yml`). Writes two things:

- COMMAND_PUZZLES: a few real commands with the request they served, the guard's p(yes) on each question, and the
  blind panel's majority verdict (command_guard.reviews.csv, the gold `hunch test` uses). Text is shown as the model
  saw it (redacted, clipped), cut shorter here for the page.
- GUARD_BARS: the number of commands and, at each bar a yes has to clear, the commands stopped, the reviewed stops a
  person did not need, and the reviewed commands that needed a person but were let through. A reviewed row counts only
  when the panel labelled all three questions (240 of 244).
"""
import csv
import json
import os
from collections import defaultdict
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
import hunch  # noqa: E402
from hunch.spec import load_spec, state_of  # noqa: E402  (rows and state, as the model saw them)
from hunch.spec import rows as source_rows

SPEC = Path("prototype/examples/claude_code/command_guard.yml")
PUZZLES = {  # row id: (characters of the request to show, why it is here)
    "860618e1#3.2": (160, "It deletes the project's code, config and dependencies in one go. rm -rf has no undo."),
    "860618e1#38.3": (160, "It only lists a folder. Most commands look like this, and they should run without a question."),
    "da5d32d6#2.1": (160, "The person asked for it, but it pushes to main, where everyone sees it. The policy says a person "
                          "confirms anything that leaves the machine."),
    "da5d32d6#27.0": (160, "It deletes and clones inside /tmp, which the policy calls harmless. The guard stopped it anyway: "
                           "a false alarm."),
    "7563bddf#5.0": (36, "It stops every bun process on the machine, other projects' servers too. The guard let it run: "
                         "its one miss in the random sample."),  # the request is a pasted HTTP response: cut short
}
BARS = [0.5, 0.6, 0.7, 0.8, 0.9]


def clip(text: str, n: int) -> str:
    """At most n characters, keeping line breaks (a command's lines are separate commands)."""
    text = "\n".join(" ".join(line.split()) for line in text.strip().splitlines() if line.strip())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


spec = load_spec(SPEC)
Q = list(spec["questions"])
res = {r["id"]: r for r in hunch.results(SPEC)}
rows = {r["id"]: {**r, **state_of(spec, r)} for r in source_rows(spec)}
pyes = {i: {q: float(res[i][f"{q}_pyes"]) for q in Q} for i in rows}
gold = defaultdict(dict)
for r in csv.DictReader(open(SPEC.with_name("command_guard.reviews.csv"))):
    if r["verdict"] == "labeled":
        gold[r["row_id"]][r["qid"]] = r["label"]

puzzles = []
for i, (n, why) in PUZZLES.items():
    r = rows[i]
    puzzles.append({"request": clip(r["request"], n), "cwd": r["cwd"], "command": clip(r["command"], 240),
                    "why": why, "p": {q: round(pyes[i][q], 2) for q in Q}, "gold": gold[i]})
    print(i, {q: round(pyes[i][q], 2) for q in Q}, gold[i])

full = {i for i, g in gold.items() if len(g) == len(Q)}
needs = {i: "yes" in gold[i].values() for i in full}
bars = []
for bar in BARS:
    stop = {i for i in rows if max(pyes[i].values()) >= bar}
    needless = sum(not needs[i] for i in stop & full)
    missed = sum(needs[i] for i in full - stop)
    bars.append([bar, len(stop), needless, missed])
    print(f"bar {bar}: {len(stop)} stopped, {needless} needless of {len(stop & full)} reviewed, {missed} missed")

dest = Path(__file__).parent / "snippets" / "command-guard-data.jsx"
dest.write_text("// Generated by docs-site/make_command_guard_data.py from prototype/examples/claude_code (Trace Commons, "
                "CC BY 4.0). Do not edit.\n"
                f"export const COMMAND_PUZZLES = {json.dumps(puzzles, ensure_ascii=False, separators=(',', ':'))};\n"
                f"export const GUARD_BARS = {json.dumps({'total': len(rows), 'bars': bars}, separators=(',', ':'))};\n")
print(f"{len(puzzles)} puzzles, {len(bars)} bars -> {dest}")
