"""Rebuild snippets/rag-answers-data.jsx from the rag-answers example's cached answers.

    uv run --extra sql hunch run prototype/examples/rag_answers/answer_support.yml   # free when cached
    uv run --extra sql python docs-site/make_rag_answers_data.py                      # from the repo root

Asks nothing (HUNCH_MAX_COST=0): it reads the table `hunch run` wrote.

RAG_PUZZLES: five RAGTruth answers with short passages (shown in full), each with the question's p(unsupported),
whether the spec passes it, and whether the annotators marked anything in it.
RAG_MODELS: for each of the six models that wrote the answers, how many of its answers the annotators marked, how
many the question leans "unsupported" on, and how many the spec passes (act on "no" at 0.7).
"""
import json
import os
import re
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
import hunch  # noqa: E402

SPEC = "prototype/examples/rag_answers/answer_support.yml"
PUZZLES = {  # RAGTruth answer id: what to notice
    "16360": "No passage says which line of the 1040. The answer adds “line 6”.",
    "16452": "None of the passages gives a headquarters, and saying so is supported.",
    "16121": "Sealing holes with steel wool is in the passages. Humane traps and peppermint oil are not.",
    "15737": "The Celsius figures are conversions; no passage states them. The annotators let that pass. "
             "The question doesn't.",
    "16056": "The annotators marked something in this answer, and the check passed it: one of four such answers "
             "among the 489 it passed. The data records that a span was marked, not which one.",
}
MODELS = {  # RAGTruth's model name: how the page writes it
    "llama-2-7b-chat": "Llama 2 7B chat", "llama-2-13b-chat": "Llama 2 13B chat",
    "llama-2-70b-chat": "Llama 2 70B chat", "mistral-7B-instruct": "Mistral 7B instruct",
    "gpt-3.5-turbo-0613": "GPT-3.5 turbo", "gpt-4-0613": "GPT-4",
}

rows = hunch.results(SPEC)
by_id = {r["id"]: r for r in rows}
puzzles = []
for i, why in PUZZLES.items():
    r = by_id[i]
    passages = [p.strip() for p in re.split(r"passage \d+:", r["passages"]) if p.strip()]
    assert len(r["passages"]) < 1100, f"{i}: passages too long to show in full"
    puzzles.append({"id": i, "model": MODELS[r["model"]], "question": r["question"], "passages": passages,
                    "answer": r["answer"].strip(), "p": float(r["unsupported_pyes"]),
                    "passed": r["unsupported"] == "no" and r["unsupported_route"] == "act",
                    "marked": r["gold_unsupported"] == "yes", "why": why})
    print(i, r["model"], "p(unsupported)", r["unsupported_pyes"], r["unsupported_route"], "marked", r["gold_unsupported"])

models = []
for m, name in MODELS.items():
    rs = [r for r in rows if r["model"] == m]
    passed = sum(r["unsupported"] == "no" and r["unsupported_route"] == "act" for r in rs)
    models.append([name, len(rs), sum(r["gold_unsupported"] == "yes" for r in rs),
                   sum(r["unsupported"] == "yes" for r in rs), passed])
    print(models[-1])
assert sum(m[1] for m in models) == len(rows), "a model is missing from MODELS"

dest = Path(__file__).parent / "snippets" / "rag-answers-data.jsx"
dump = lambda o: json.dumps(o, ensure_ascii=False, separators=(",", ":"))  # noqa: E731
dest.write_text("// Generated by docs-site/make_rag_answers_data.py from prototype/examples/rag_answers (RAGTruth, "
                "ParticleMedia, MIT). Do not edit.\n"
                f"export const RAG_PUZZLES = {dump(puzzles)};\n"
                "// [model, answers, marked by the annotators, flagged by the question, passed at 0.7]\n"
                f"export const RAG_MODELS = {dump(models)};\n")
print(f"{len(puzzles)} puzzles, {len(models)} models -> {dest} ({dest.stat().st_size // 1024} KB)")
