"""Rebuild snippets/banking-intents-data.jsx from the BANKING77 example's cached answers and the review panel's verdicts.

    uv run --extra sql python docs-site/make_banking_intents_data.py     # from the repo root; asks nothing (HUNCH_MAX_COST=0)

INTENT_PUZZLES: holdout messages where the model and the answer key disagree, each with both labels (in alphabetical
order, so neither source comes first), the spec's one-line description of each, the model's confidence, the panel's
verdict from intent.reviews.csv, and how many of the three blind reviewers accepted each label.
DISPUTE_SPLIT: the panel's verdicts on every disagreement, counted.
"""
import json
import os
from collections import Counter
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
from hunch import core  # noqa: E402

EXAMPLE = Path("prototype/examples/banking77")
PANEL = Path("prototype/review_panel")
PUZZLES = ["562", "2496", "2691", "2751", "22", "1404", "2197", "1337", "621"]  # holdout row ids, in the order shown

project = core.load_project(EXAMPLE / "intent.yml")
spec = project["nodes"]["intent"]
spec["source"] = (EXAMPLE / "banking77_holdout.csv").resolve()
res = core.execute(project)["intent"]
reviews = core.load_reviews(spec)
describe = spec["questions"]["intent"]["criteria"]

# votes[row id][label] = reviewers (of 3) who rated that label acceptable, from the blind panel's own answers
key = json.load(open(PANEL / "key/b77_map.json"))
votes = {}
for rev in ["opus", "sonnet_a", "sonnet_b"]:
    for a in json.load(open(PANEL / f"answers/b77_{rev}.json")):
        info = key[f"{rev}:{a['n']}"]
        for label in (info["gold"], info["jev"]):
            v = votes.setdefault(info["id"], {})
            v[label] = v.get(label, 0) + bool(a["candidates"].get(label))

rows, split = {}, Counter()
for it in res["items"]:
    label, conf, _ = core.decide(res["answers"][it["key"]])
    answer_key = it["row"]["gold_intent"]
    if label == answer_key:
        continue
    verdict = reviews[("intent", it["id"])]["verdict"]  # every disagreement was reviewed
    split[verdict] += 1
    rows[it["id"]] = {"text": it["state"]["text"], "key": answer_key, "model": label, "p": round(conf, 2),
                      "verdict": {"model_right": "model", "key_right": "key", "both_ok": "both"}[verdict]}

out = []
for rid in PUZZLES:
    r = rows[rid]
    labels = sorted([r["key"], r["model"]])
    # [label, the spec's description of it, reviewers of 3 who accepted it, is the answer key's]
    r["labels"] = [[x, describe[x], votes[rid][x], int(x == r["key"])] for x in labels]
    out.append({k: r[k] for k in ("text", "labels", "model", "p", "verdict")})
    print(rid, r["verdict"], r["key"], "|", r["model"], r["p"], [v[2] for v in r["labels"]], r["text"][:50])

split = [["The model was right, the answer key wrong", split["model_right"]],
         ["Both labels fit the message", split["both_ok"]],
         ["The answer key was right, the model wrong", split["key_right"]]]
dest = Path(__file__).parent / "snippets" / "banking-intents-data.jsx"
dest.write_text("// Generated by docs-site/make_banking_intents_data.py from prototype/examples/banking77 (BANKING77, PolyAI, "
                "CC BY 4.0) and prototype/review_panel. Do not edit.\n"
                f"export const INTENT_PUZZLES = {json.dumps(out, ensure_ascii=False, separators=(',', ':'))};\n"
                f"export const DISPUTE_SPLIT = {json.dumps(split, ensure_ascii=False, separators=(',', ':'))};\n")
print(f"{sum(n for _, n in split)} disagreements: {split}")
print(f"{len(out)} puzzles -> {dest} ({dest.stat().st_size} bytes)")
