"""Rebuild snippets/nda-review-data.jsx from the NDA example's cached answers.

    uv run --extra sql python docs-site/make_nda_review_data.py     # from the repo root; asks nothing (HUNCH_MAX_COST=0)

Both wordings of the spec (nda_review.yml and first/nda_review.yml) are read on both splits with a dry run, which
only reads the store: a missing answer stops the script instead of asking. It writes three things:
- NDA_PUZZLES: four test contracts for the "must it be marked?" question, each a verbatim excerpt (whitespace
  collapsed), the lawyers' label, the answer of each wording with its three probabilities, and how many other words
  in the contract are about marking;
- NDA_FIX: on the dev contracts the lawyers labelled not_mentioned for marking, each wording's answer;
- NDA_CLAUSES: accuracy of each wording on the 61 dev contracts, per clause.
"""
import csv
import json
import os
import re
import sys
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
import hunch  # noqa: E402
from hunch.core import execute  # noqa: E402

csv.field_size_limit(sys.maxsize)
EXAMPLE = Path("prototype/examples/nda_review")
Q = "must_be_marked"
MARKING = re.compile(r"(?i)\b(mark(ed|s|ing)?|designat\w*|legend|label\w*|identified as)\b")

PUZZLES = [  # test contract, where its excerpt starts and ends, and why it is here
    ("181", "“Confidential Information” shall mean all", "pursuant to the Purpose.",
     "It covers everything, so a reader infers unmarked information counts. The contract never says so, and that "
     "is what the lawyers label."),
    ("117", "For convenience, the Disclosing", "equivalent designation.",
     "Marking is allowed but not required, so unmarked information is protected, and the contract puts that in words."),
    ("157", "information disclosed by the Disclosing Party will be", "non-tangible form",
     "Only information designated \"Confidential\", or confirmed in writing, counts."),
    ("51", "All information disclosed by a Party", "by the disclosing Party.",
     "Everything counts unless the discloser says otherwise. hunch reads that as an answer, and is sure of it; the "
     "lawyers' label says the contract never mentions marking."),
]


def answers(spec: str, source: str) -> tuple[dict, dict]:
    rows = list(csv.DictReader(open(EXAMPLE / source, encoding="utf-8")))
    res = execute(hunch.load(EXAMPLE / spec), rows_in=rows, dry=True)["nda_review"]
    out = {}
    for it in res["items"]:
        a = res["answers"].get(it["key"])
        if a is None:
            sys.exit(f"{spec} on {source}: no cached answer for contract {it['id']} {it['qid']}")
        out[(str(it["id"]), it["qid"])] = (a["choice"], {k: round(v, 2) for k, v in a["probabilities"].items()})
    return out, {r["id"]: r for r in rows}


new_test, test = answers("nda_review.yml", "contractnli_test.csv")
old_test, _ = answers("first/nda_review.yml", "contractnli_test.csv")
new_dev, dev = answers("nda_review.yml", "contractnli_dev.csv")
old_dev, _ = answers("first/nda_review.yml", "contractnli_dev.csv")

puzzles = []
for cid, start, end, why in PUZZLES:
    text = re.sub(r"\s+", " ", test[cid]["text"])
    i = text.find(start)
    j = text.find(end, i) + len(end)
    if i < 0 or j < len(end):
        sys.exit(f"contract {cid}: excerpt not found")
    excerpt = text[i:j]
    elsewhere = len(MARKING.findall(text[:i] + " " + text[j:]))
    puzzles.append({"id": cid, "chars": len(text), "excerpt": excerpt, "elsewhere": elsewhere, "why": why,
                    "gold": test[cid][f"gold_{Q}"], "hunch": new_test[(cid, Q)], "first": old_test[(cid, Q)]})
    print(f"#{cid} gold={puzzles[-1]['gold']} hunch={new_test[(cid, Q)]} first={old_test[(cid, Q)][0]} "
          f"elsewhere={elsewhere} ({len(excerpt)} chars)")

fix = [[old_dev[(i, Q)][0], new_dev[(i, Q)][0]] for i, r in dev.items() if r[f"gold_{Q}"] == "not_mentioned"]
print(f"fix: {len(fix)} dev contracts labelled not_mentioned; first wording says_otherwise on "
      f"{sum(o == 'says_otherwise' for o, _ in fix)}, reworded on {sum(n == 'says_otherwise' for _, n in fix)}")

clauses = []
for q in ["must_be_marked", "advisors_allowed", "copies_allowed", "may_keep_after_return", "survives_termination"]:
    first = sum(old_dev[(i, q)][0] == r[f"gold_{q}"] for i, r in dev.items())
    now = sum(new_dev[(i, q)][0] == r[f"gold_{q}"] for i, r in dev.items())
    clauses.append([q, first, now, len(dev)])
    print(f"{q}: {first}/{len(dev)} -> {now}/{len(dev)}  ({100 * first / len(dev):.1f}% -> {100 * now / len(dev):.1f}%)")

dest = Path(__file__).parent / "snippets" / "nda-review-data.jsx"
dump = lambda x: json.dumps(x, ensure_ascii=False, separators=(",", ":"))  # noqa: E731
dest.write_text("// Generated by docs-site/make_nda_review_data.py from prototype/examples/nda_review (ContractNLI, "
                "Hitachi America, Ltd., CC BY 4.0). Do not edit.\n"
                f"export const NDA_PUZZLES = {dump(puzzles)};\n"
                f"export const NDA_FIX = {dump(fix)};\n"
                f"export const NDA_CLAUSES = {dump(clauses)};\n")
print(f"-> {dest} ({dest.stat().st_size // 1024} KB)")
