"""Rebuild snippets/stale-comments-data.jsx from the stale-comments example's cached answers.

    uv run --extra sql python docs-site/make_stale_comments_data.py   # from the repo root; asks nothing (dry run)

STALE_PUZZLES: a few hand-checked comments, each with its method before and after the commit (as a line diff), the
parser's `signature_change`, what each of the three specs answered, and the hand-checked answer (`gold_checked`).
STALE_VIEWS: for each spec, how many of the 300 hand-checked comments it got wrong, in total and by kind.
"""
import difflib
import json
import os
import textwrap
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
from hunch.core import execute, load_project  # noqa: E402

EXAMPLE = Path("prototype/examples/stale_comments")
VIEWS = [  # spec, what the model sees
    ("code_only/stale_comment.yml", "The comment and the code now"),
    ("before_after/stale_comment.yml", "…and the code before the commit"),
    ("stale_comment.yml", "…and the parser's facts"),
]
PUZZLES = {  # row id: why it is here
    "bobmcwhirter_drools-19-4957":
        "The method now returns a Package, not a RuleSet, and the comment still promises the rule set.",
    "apache_drill-828-Param-0":
        "The commit changed path from a String to a Path. The comment is about fs, which it didn't touch.",
    "JodaOrg_joda_time-457-Param-0":
        "The parameter is now called duration, and the comment still names length. "
        "With the code before and after but without the parser's note of the rename, the model leaned towards fine.",
    "LawnchairLauncher_Lawnchair-28-FirstSentence-0":
        "It takes a Context instead of a Launcher, but it still inflates R.layout.user_folder into a new folder. "
        "Without the parser's facts, the model called this comment stale.",
    "yahoo_elide-2-Associations-FirstSentence":
        "The commit fixed the spelling of the method it calls, isSharable to isShareable. The person who checked it "
        "counted the comment's “sharable” as stale; hunch was sure it was fine. It is one of its most confident "
        "mistakes against the hand-checked answers.",
}
KINDS = ["summary", "param", "return"]


def code(text: str) -> list[str]:
    lines = textwrap.dedent(text.expandtabs(4)).rstrip().split("\n")
    return [ln.rstrip() for ln in lines]


def diff(old: str, new: str) -> list[list[str]]:
    """[op, line]: ' ' in both, '-' only before the commit, '+' only after."""
    a, b = code(old), code(new)
    out = []
    for op, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
        if op == "equal":
            out += [[" ", ln] for ln in a[i1:i2]]
        else:
            out += [["-", ln] for ln in a[i1:i2]] + [["+", ln] for ln in b[j1:j2]]
    return out


answers = {spec: {r["id"]: r for r in execute(load_project(EXAMPLE / spec), dry=True)["stale_comment"]["rows"]}
           for spec, _ in VIEWS}
final = answers[VIEWS[-1][0]]
gold = [i for i, r in final.items() if r["gold_checked"]]
views = []
for spec, label in VIEWS:
    rows = answers[spec]
    if any(rows[i]["stale"] is None for i in gold):
        raise SystemExit(f"{spec}: answers missing from the store; `hunch run` it first")
    wrong = {k: sum(rows[i]["stale"] != rows[i]["gold_checked"] for i in gold if rows[i]["kind"] == k) for k in KINDS}
    views.append({"label": label, "wrong": sum(wrong.values()), "of": len(gold), "by_kind": wrong})
    print(f"{spec}: {sum(wrong.values())} wrong of {len(gold)} {wrong}")

puzzles = []
for i, why in PUZZLES.items():
    r = final[i]
    if not r["gold_checked"]:
        raise SystemExit(f"{i} is not hand-checked")
    puzzles.append({
        "kind": r["kind"], "comment": r["comment"], "diff": diff(r["old_code"], r["new_code"]),
        "facts": r["signature_change"], "gold": r["gold_checked"],
        "p": [answers[s][i]["stale_pyes"] for s, _ in VIEWS],  # p(stale) with each view, the last is the shipped spec
        "sure": r["stale_route"] == "act", "why": why,
    })
    print(r["kind"], r["comment"][:40], "gold", r["gold_checked"], puzzles[-1]["p"], r["stale_route"])

dest = Path(__file__).parent / "snippets" / "stale-comments-data.jsx"
dest.write_text("// Generated by docs-site/make_stale_comments_data.py from prototype/examples/stale_comments (Panthaplackel "
                "et al., AAAI 2021, MIT; each method under its own project's licence). Do not edit.\n"
                f"export const STALE_PUZZLES = {json.dumps(puzzles, ensure_ascii=False, separators=(',', ':'))};\n"
                f"export const STALE_VIEWS = {json.dumps(views, ensure_ascii=False, separators=(',', ':'))};\n")
print(f"{len(puzzles)} puzzles, {len(views)} views -> {dest}")
