"""Rebuild snippets/pair-puzzles.jsx from the product-matching example's cached answers.

    uv run --extra sql python docs-site/make_pair_data.py     # from the repo root; asks nothing (HUNCH_MAX_COST=0)

Also snippets/sieve-data.jsx: every Buy product seen from one Abt product (the turntable), with the two clues
and, for the five the rules keep, the question's answer: the data of the PairSieve animation.

Each puzzle is one Abt product and the candidates the rules kept for it, in the rules' order, with the question's
answer on each and whether it is the match: the benchmark's answer key, overruled where the review panel decided
otherwise (the same gold `hunch test` uses). A puzzle can have no match among its candidates.
"""
import csv
import json
import os
import sys
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
EXAMPLE = Path("prototype/examples/product_matching")
sys.path.insert(0, str(EXAMPLE))
import candidates  # noqa: E402

import hunch.sql  # noqa: E402

PUZZLES = {  # Abt product: why it is here
    "32875": "The codes are one digit apart, so the rules pick a cable for a case.",
    "37091": "The benchmark says the T300 is its match; the review panel says no camera here is.",
    "24493": "The rules pick the wrong phone; the right one is third.",
    "552": "The same record player, written two ways, next to a sibling model.",
}

con = candidates.connect()
hunch.sql.register(con, EXAMPLE / "same_product.yml", max_cost=0)
con.execute(f"create table pairs as {candidates.PAIRS}")
ids = ", ".join(f"'{i}'" for i in PUZZLES)
rows = con.execute(f"""
    select abt_id, abt_name, buy_name, rank::int, d.same.label, d.same.p, gold_same, buy_id
    from (select *, same_product(abt_name, abt_description, abt_price, buy_name, buy_manufacturer,
                                 buy_description, buy_price) as d from pairs where abt_id in ({ids}))
    order by abt_id, rank::int""").fetchall()

verdicts = {r["row_id"]: r["label"] for r in csv.DictReader(open(EXAMPLE / "same_product.reviews.csv"))
            if r["verdict"] == "labeled"}  # the last verdict wins, as in hunch test
buys = {a: [r[7] for r in rows if r[0] == a] for a in PUZZLES}
out = []
for abt_id, why in PUZZLES.items():
    rs = [r for r in rows if r[0] == abt_id]
    if not rs:
        sys.exit(f"no candidates for Abt product {abt_id}")
    # candidate: [name, p(yes) from the question, the benchmark's match?]; the rules' pick is the first
    cands = [[r[2], round(r[5] if r[4] == "yes" else 1 - r[5], 2), int(verdicts.get(f"{abt_id}~{b}", r[6]) == "yes")]
             for r, b in zip(rs, buys[abt_id])]
    out.append({"product": rs[0][1], "why": why, "candidates": cands})
    print(rs[0][1], "->", [(c[0][:30], c[1], c[2]) for c in cands])

dest = Path(__file__).parent / "snippets" / "pair-puzzles.jsx"
dest.write_text("// Generated by docs-site/make_pair_data.py from prototype/examples/product_matching (Abt-Buy, University of "
                "Leipzig, Creative Commons). Do not edit.\n"
                f"export const PAIR_PUZZLES = {json.dumps(out, ensure_ascii=False, separators=(',', ':'))};\n")
print(f"{len(out)} puzzles -> {dest}")

SIEVE = "552"  # Sony Turntable - PSLX350H
all_buy = con.execute(f"""
    select b.id, b.name, shared_words(a.name, b.name || ' ' || b.manufacturer) > 0 as shares_word,
           shares_code(a.name, b.name || ' ' || b.description) as code,
           word_overlap(a.name, b.name || ' ' || b.manufacturer) as overlap
    from abt a, buy b where a.id = '{SIEVE}' order by b.id""").fetchall()
kept = {r[7]: (r[3], round(r[5] if r[4] == "yes" else 1 - r[5], 2),
               int(verdicts.get(f"{SIEVE}~{r[7]}", r[6]) == "yes"))
        for r in con.execute(f"""
    select abt_id, abt_name, buy_name, rank::int, d.same.label, d.same.p, gold_same, buy_id
    from (select *, same_product(abt_name, abt_description, abt_price, buy_name, buy_manufacturer,
                                 buy_description, buy_price) as d from pairs where abt_id = '{SIEVE}')""").fetchall()}
# [name, shares a word, shares the code, word overlap, rank if kept (else 0), p(same) if kept (else -1), is the match]
dots = [[r[1][:60], int(r[2]), int(bool(r[3])), round(r[4] or 0, 2), kept.get(r[0], (0,))[0],
         kept.get(r[0], (0, -1))[1], kept.get(r[0], (0, -1, 0))[2]] for r in all_buy]
sieve = {"product": con.execute(f"select name from abt where id = '{SIEVE}'").fetchone()[0], "buy": dots}
dest = Path(__file__).parent / "snippets" / "sieve-data.jsx"
dest.write_text("// Generated by docs-site/make_pair_data.py from prototype/examples/product_matching (Abt-Buy, University of "
                "Leipzig, Creative Commons). Do not edit.\n"
                f"export const SIEVE = {json.dumps(sieve, ensure_ascii=False, separators=(',', ':'))};\n")
print(f"sieve: {len(dots)} Buy products, {sum(d[1] for d in dots)} share a word, "
      f"{sum(d[2] for d in dots)} share the code, {sum(1 for d in dots if d[4])} kept -> {dest} ({dest.stat().st_size // 1024} KB)")
