"""Rebuild snippets/screening-data.jsx from the screening example's cached answers.

    uv run python docs-site/make_screening_data.py     # from the repo root, after fetch.py and baseline.py; asks nothing

It writes:
- SCREEN_PUZZLE: six papers the Wilson disease review screened, by title only (titles are OpenAlex metadata, CC0;
  no abstract is published), each with the screeners' decision, whether it ended up in the review, and hunch's p(yes);
- SCREEN_CURVES: per review, the share of the papers that ended up in the review found after reading each half
  percent of the pile, in hunch's order and in active learning's (the run of baseline.py's three whose last find is
  the median).
"""
import csv
import json
import sys
from pathlib import Path

import numpy as np

EXAMPLE = Path("prototype/examples/screening")
sys.path.insert(0, str(EXAMPLE))
import measure  # noqa: E402  (sets HUNCH_MAX_COST=0 before importing hunch)

csv.field_size_limit(10**8)
PUZZLE = [  # Wilson disease review: why each paper is here
    ("W2090882839", "A head-to-head trial of two of the four drugs: in the review, and hunch was sure."),
    ("W4292361613", "A whole conference's poster abstracts. The criteria exclude abstract-only publications; the screeners kept it anyway, and it did not make the review."),
    ("W2906450930", "A single hospital's patients over 12 years. It made the review, so it compared treatments, which the title doesn't say. Of all the papers in the review, this is the one hunch was least sure of."),
    ("W2025321071", "Another group of patients followed over time. The screeners kept it too; after reading the full text, the reviewers left it out."),
    ("W2421531636", "Zinc against penicillamine sounds exactly right, and hunch said yes. The screeners dropped it; with no abstract to read, hunch had only the title."),
    ("W2193363560", "A genetics study of schizophrenia that the literature search swept in. Nobody's yes."),
]
TITLES = {"anxiety": "Anxiety therapy", "diet_risk": "Diet and risk", "wilson": "Wilson disease"}


def found(inc, order, grid):
    """Share of the review's papers found after reading each share of the pile, in this order."""
    c = np.cumsum(inc[order]) / inc.sum()
    return [round(float(c[min(int(g * len(order)), len(order)) - 1]) * 100, 1) if g > 0 else 0.0 for g in grid]


grid = [i / 200 for i in range(201)]
curves = {}
for name, review in measure.REVIEWS.items():
    rows = list(csv.DictReader(open(EXAMPLE / f".cache/{review}.csv")))
    p = measure.p_yes(EXAMPLE / f"{name}.yml")
    inc = np.array([r["included"] == "yes" for r in rows], float)
    hunch_order = np.argsort(-np.array([p[r["id"]] for r in rows]), kind="stable")
    pos = {r["id"]: i for i, r in enumerate(rows)}
    runs = []
    for f in sorted((EXAMPLE / ".cache" / "asreview").glob(f"{review}_s*.json")):
        seen = [pos[i] for i in json.load(open(f))]
        done = set(seen)
        o = np.array(seen + [i for i in range(len(rows)) if i not in done])
        runs.append((measure.read_for(inc[o], -np.arange(len(o)), 1.0)[0], o))
    runs.sort(key=lambda r: r[0])
    curves[name] = {"title": TITLES[name], "papers": len(rows), "inReview": int(inc.sum()),
                    "hunch": found(inc, hunch_order, grid), "active": found(inc, runs[len(runs) // 2][1], grid)}
    print(name, "hunch all at", next(g for g, v in zip(grid, curves[name]["hunch"]) if v >= 100),
          "active all at", next(g for g, v in zip(grid, curves[name]["active"]) if v >= 100))

rows = {r["id"]: r for r in csv.DictReader(open(EXAMPLE / ".cache/Appenzeller-Herzog_2019.csv"))}
p = measure.p_yes(EXAMPLE / "wilson.yml")
puzzle = [{"title": rows[i]["title"], "kept": rows[i]["gold"] == "yes", "inReview": rows[i]["included"] == "yes",
           "p": round(p[i], 2), "why": why} for i, why in PUZZLE]
dest = Path(__file__).parent / "snippets" / "screening-data.jsx"
dest.write_text("// Generated by docs-site/make_screening_data.py from prototype/examples/screening (SYNERGY, CC0; titles are "
                "OpenAlex metadata, CC0). Do not edit.\n"
                f"export const SCREEN_PUZZLE = {json.dumps(puzzle, ensure_ascii=False)};\n"
                f"export const SCREEN_CURVES = {json.dumps(curves, separators=(',', ':'))};\n")
print(json.dumps(puzzle, ensure_ascii=False)[:600])
