"""Rebuild snippets/dial-rows.jsx from the BANKING77 example's cached answers, with the same gold as `hunch test`.

    uv run python docs-site/make_widget_data.py     # from the repo root; asks nothing (HUNCH_MAX_COST=0)
"""
import json
import os
from pathlib import Path

os.environ["HUNCH_MAX_COST"] = "0"
from hunch.answers import attach_gold, conf_of, decide, hit, load_reviews  # noqa: E402
from hunch.execute import execute  # noqa: E402
from hunch.spec import DIAL, load_project  # noqa: E402

project = load_project(Path("prototype/examples/banking77/intent.yml"))
res = execute(project)["intent"]
attach_gold(res["items"], load_reviews(project["nodes"]["intent"]))
rows = []
for it in res["items"]:
    if it["qid"] != "intent" or not it["gold"]:
        continue
    a = res["answers"][it["key"]]
    ok = hit(it, a, "gold")
    # [confidence, right?, model answer, gold if wrong, start of the message]
    rows.append([round(conf_of(it, a), 3), int(ok), decide(a)[0], "" if ok else " or ".join(sorted(it["gold"])) if isinstance(it["gold"], (set, frozenset)) else str(it["gold"]), it["state"]["text"][:70]])
rows.sort(key=lambda r: r[0])

out = Path(__file__).parent / "snippets" / "dial-rows.jsx"
out.write_text("// Generated by docs-site/make_widget_data.py from prototype/examples/banking77 (BANKING77, PolyAI, CC BY 4.0). Do not edit.\n"
               f"export const DIAL_ROWS = {json.dumps(rows, ensure_ascii=False, separators=(',', ':'))};\n")
for t in DIAL:
    auto = [r for r in rows if r[0] >= t]
    print(f"{t:.2f}  automated {len(auto) / len(rows):.1%}  wrong {sum(not r[1] for r in auto) / len(auto):.1%}")
print(f"{len(rows)} rows -> {out} ({out.stat().st_size // 1024} KB)")
